void Nhap(int a[], int &n);
void Xuat(int a[], int n);
void Xoaphantu(int a[], int &n, int &i, int &k);
void Sapxep(int a[], int n);
void Dem(int a[], int n);
void Demtrongkhoangk(int a[], int n, int k);
void Timslthu2(int a[], int n);
void PTxhnhieunhat(int a[], int n);
int Demsoxuathien(int a[], int n, int x);
int Timsominxy(int a[], int n, int &x, int &y);
int Tongkptlientiep(int a[], int n, int thutu, int k);
void Tongkptlientiepmax(int a[], int n, int &k);
void Daonguocmang(int a[], int n);
void Sapxepchanle(int a[], int n);
void swap(int &a, int &b);
bool Sochinhphuong(int a);
void SxSochinhphuong(int a[], int n);
void SNTtrongmang(int a[], int n);
void SNTmin(int a[], int n);
void Soduongmin(int a[], int n);
void Soammax(int a[], int n);
bool KTtangdan(int a[], int n);
void Indaycontangday(int a[], int n);
void Xuatmangcon(int a[], int n);
